package _archive

//import (
//	"github.com/mikeschinkel/go-cliutil"
//	"github.com/mikeschinkel/gomion/gommod/gompkg"
//)
//
//var _ cliutil.CommandHandler = (*InitCmd)(nil)
//
//// InitCmd creates .gomion/config.json files for repos
//type InitCmd struct {
//	*cliutil.CmdBase
//	filePath string
//	dir      string
//}
//
//func init() {
//	var cmd *InitCmd
//	var err error
//
//	cmd = &InitCmd{
//		filePath: "",
//		dir:      "",
//	}
//
//	cmd.CmdBase = cliutil.NewCmdBase(cliutil.CmdArgs{
//		//Order:       5,
//		Name: "init",
//		//Usage:       "init [<dir>] | init --file <path>",
//		Description: "Initialize .gomion/config.json for repos (scans directory or reads from file)",
//		ArgDefs: []*cliutil.ArgDef{
//			{
//				Name:     "dir",
//				Usage:    "Directory to scan and initialize (defaults=scan_dirs in ~/.config/gomion)",
//				Required: false,
//				String:   &cmd.dir,
//				Example:  "~/Projects",
//			},
//		},
//		FlagSets: []*cliutil.FlagSet{
//			{
//				Name: "init",
//				FlagDefs: []cliutil.FlagDef{
//					{
//						Name:     "file",
//						Shortcut: 'f',
//						Usage:    "RelPath to file — generated by 'scan' command — containing go.mod paths (one per line)",
//						String:   &cmd.filePath,
//						Required: false,
//					},
//				},
//			},
//		},
//	})
//
//	err = cliutil.RegisterCommand(cmd)
//	if err != nil {
//		panic(err)
//	}
//}
//
//// Handle executes the init command
//func (c *InitCmd) Handle() (err error) {
//	//var config *gompkg.Config
//	var result *gompkg.InitReposResult
//
//	// Initialize repositories
//	result, err = gompkg.Init(gompkg.InitArgs{
//		FilePath: c.filePath,
//		DirPath:  c.dir,
//		Writer:   c.Writer,
//		Logger:   c.Logger,
//		Config:   c.Config.(*gompkg.Config),
//	})
//	if err != nil {
//		goto end
//	}
//
//	// Print summary
//	c.Writer.Printf("\nSummary:\n")
//	c.Writer.Printf("  Initialized: %d repos\n", result.Initialized)
//	c.Writer.Printf("  Skipped:     %d repos\n", result.Skipped)
//
//end:
//	return err
//}
